/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Feedback {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'approved' : boolean,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'owner' : Principal,
  'name' : string,
  'email' : string,
  'address' : string,
  'notes' : string,
  'timestamp' : Time,
  'category' : OrderCategory,
  'phone' : string,
  'budget' : string,
}
export type OrderCategory = { 'bedroom' : null } |
  { 'bathroom' : null } |
  { 'office' : null } |
  { 'painting' : null } |
  { 'kitchen' : null } |
  { 'falseCeiling' : null } |
  { 'lighting' : null } |
  { 'livingRoom' : null } |
  { 'civilWork' : null } |
  { 'wallDesign' : null } |
  { 'electricalWork' : null } |
  { 'flooring' : null } |
  { 'modularWardrobe' : null } |
  { 'modularWork' : null };
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'getAllFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getApprovedFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByCategory' : ActorMethod<[OrderCategory], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<[string, bigint, string], bigint>,
  'submitOrder' : ActorMethod<
    [string, string, string, string, OrderCategory, string, string],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];